
# Stage 1: Build Frontend
FROM node:24-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies cleanly
RUN npm ci

# Copy source code
COPY . .

# Build React/Vite app
RUN npm run build

# Stage 2: Nginx Runtime
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
