FROM node:24-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

FROM node:24-alpine AS runtime

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

EXPOSE 5000

CMD ["node", "src/app.js"]
