# Use lightweight Node.js image
FROM node:24-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy backend source code
COPY . .

# Expose port
EXPOSE 5000

# Start backend
CMD ["node", "src/app.js"]
